version: '2'
services:
  master:
    build: ./hadoop-master
    container_name: "master"
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.3"
  mfsmaster:
    image: moosefs/master
    container_name: "mfsmaster"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.2"
  mfschunkhadoop_a1:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_a1"
    hostname: mfschunkhadoop_a1
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - RUN_EXAMPLE=1
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.11"
  mfschunkhadoop_a2:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_a2"
    hostname: mfschunkhadoop_a2
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.12"
  mfschunkhadoop_a3:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_a3"
    hostname: mfschunkhadoop_a3
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.13"
  mfschunkhadoop_b1:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_b1"
    hostname: mfschunkhadoop_b1
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.21"
  mfschunkhadoop_b2:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_b2"
    hostname: mfschunkhadoop_b2
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.22"
  mfschunkhadoop_b3:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_b3"
    hostname: mfschunkhadoop_b3
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.23"
  mfschunkhadoop_c1:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_c1"
    hostname: mfschunkhadoop_c1
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.31"
  mfschunkhadoop_c2:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_c2"
    hostname: mfschunkhadoop_c2
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.32"
  mfschunkhadoop_c3:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoop_c3"
    hostname: mfschunkhadoop_c3
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.33"
networks:
  mfsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
