version: '2'
services:
  master:
    build: ./hadoop-master
    container_name: "master"
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    links:
      - mfsmaster
    networks:
      mfsnet:
        ipv4_address: "172.20.0.3"
  mfsmaster:
    image: moosefs/master
    container_name: "mfsmaster"
    networks:
      mfsnet:
        ipv4_address: "172.20.0.2"
  mfschunkhadoopa1:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopa1"
    hostname: mfschunkhadoopa1
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - RUN_EXAMPLE=1
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.11"
  mfschunkhadoopa2:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopa2"
    hostname: mfschunkhadoopa2
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.12"
  mfschunkhadoopa3:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopa3"
    hostname: mfschunkhadoopa3
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.13"
  mfschunkhadoopb1:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopb1"
    hostname: mfschunkhadoopb1
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.21"
  mfschunkhadoopb2:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopb2"
    hostname: mfschunkhadoopb2
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.22"
  mfschunkhadoopb3:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopb3"
    hostname: mfschunkhadoopb3
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.23"
  mfschunkhadoopc1:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopc1"
    hostname: mfschunkhadoopc1
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.31"
  mfschunkhadoopc2:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopc2"
    hostname: mfschunkhadoopc2
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.32"
  mfschunkhadoopc3:
    build: ./moosefs-chunkserver-client-hadoop-slave
    container_name: "mfschunkhadoopc3"
    hostname: mfschunkhadoopc3
    privileged: true
    stdin_open: true
    tty: true
    links:
      - mfsmaster
      - master
    networks:
      mfsnet:
        ipv4_address: "172.20.0.33"
networks:
  mfsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
